### ISSUE TITLE
Command always fails

### ISSUE THREAD

**Issue by rien333** [fogine/udiskie-dmenu#8]
Not sure if it's my setup (although I haven't changed anything), but `udiskie-dmenu` basically always errors. It doesn't matter what device is plugged in, nor if there are no devices present at all:

```console
$ udiskie-dmenu
udiskie-info -C -2 -a -o '"label":"{ui_label}", "isLuks":"{is_luks}", "mountPath": "{mount_path}"' errror: Usage:
    udiskie-info [options] [-o OUTPUT] [-f FILTER]... (-a | DEVICE...)
    udiskie-info (--help | --version)
```

Can you reproduce? Or do  you know what's wrong?

**Comment by rien333** [comment]
Think I got it. `udiskie-info -h` lists no `-2` flag. I'm not sure what purpose it once had, but it seems to have been removed. Removing the `-2` from the `runCommand(udiskie-info ...`  call seems to rid of the error.

**Comment by rien333** [comment]
Ah, upstream `udiskie-info` probably removed udisk1 support. Arch linux doesn't really support it anymore either. Maybe you should remove support for it as well?

**Comment by fogine** [comment]
Thanks for the repport @rien333 , you are correct.
Could you make a PR which removes the option?

**Comment by rien333** [comment]
Sure! Are you okay with completely dropping udisk1 support?

**Comment by fogine** [comment]
Yeah, older versions of udiskie-dmenu will still support it.
